#!/bin/bash
set -e

mkdir -p ~/src
cd ~/src

if [ ! -d "rethinkdb" ]; then
    echo "---- INSTALLING: dependencies for rethinkdb"
    sudo apt-get install --assume-yes g++ protobuf-compiler protobuf-c-compiler libprotobuf-dev libv8-dev libgoogle-perftools-dev make libprotoc-dev default-jre libboost-dev python-yaml
    echo "---- INSTALLING: rethinkdb"
    git clone -b v1.7.x https://github.com/rethinkdb/rethinkdb.git
    cd rethinkdb
    ./configure
    make
fi
