#!/bin/bash
set -e

mkdir -p ~/src && cd ~/src

DTRACE='dtrace4linux'

if [ ! -d "$DTRACE" ]; then
    echo "---- INSTALLING: $DTRACE"
    git clone git://github.com/dtrace4linux/linux.git "$DTRACE"
    cd "$DTRACE"
    sudo ./tools/get-deps.pl
    make all
    sudo make install
    sudo make load
else
    echo "---- INSTALLING: $DTRACE already installed, SKIPPING!"
fi

