#!/bin/bash
set -e

echo "---- INSTALLING: updating git submodules"
git submodule init
git submodule update

echo "---- INSTALLING: setting up folder structure"
mkdir -p ~/tmp

echo "---- INSTALLING: symlink for ~/.bashrc"
ln -fs ~/dotfiles/bash/bashrc ~/.bashrc

echo "---- INSTALLING: symlink for ~/.gitconfig"
ln -fs ~/dotfiles/git/gitconfig ~/.gitconfig

echo "---- INSTALLING: update apt-get"
sudo apt-get update --assume-yes

echo "---- INSTALLING: build-essential"
sudo apt-get install --assume-yes build-essential

echo "---- INSTALLING: g++"
sudo apt-get install --assume-yes g++

echo "---- INSTALLING: pkg-config"
sudo apt-get install --assume-yes pkg-config

echo "---- INSTALLING: cairo stuff"
sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev

echo "---- INSTALLING: ack-grep"
sudo apt-get install --assume-yes ack-grep

source ~/dotfiles/install-node
source ~/dotfiles/install-emacs

echo "---- INSTALL: Finished successfully!"
