#!/bin/bash

echo "---- (RE)INSTALLING: nvidia drivers"
sudo apt-get purge --assume-yes nvidia-current
sudo apt-get purge --assume-yes nvidia-current-updates
sudo apt-get purge --assume-yes nvidia-304
sudo apt-get purge --assume-yes nvidia-settings-304
sudo apt-get purge --assume-yes nvidia-settings
sudo apt-get purge --assume-yes nvidia-common
sudo apt-get purge --assume-yes nvidia-experimental-304
sudo apt-get purge --assume-yes nvidia-experimental-310
sudo add-apt-repository ppa:ubuntu-x-swat/x-updates -y
sudo apt-get update --assume-yes
sudo apt-get dist-upgrade --assume-yes
sudo apt-get install nvidia-current --assume-yes
