#!/bin/bash

VERSION=v${1:-1.0.1}
IOJS=iojs-${VERSION}-linux-x64
echo "> Downloading $VERSION of iojs"
curl -s https://iojs.org/dist/${VERSION}/${IOJS}.tar.xz | tar xvfJ -

echo "> Setting ownership of /usr/local to $USER"
sudo chown -R ${USER}:${USER} /usr/local

echo "> Moving extracted iojs binaries"
rm -rf /usr/local/lib/${IOJS} && mv ${IOJS} /usr/local/lib

echo "> Symlinks"
sudo ln -fs /usr/local/lib/${IOJS}/bin/iojs /usr/local/bin/iojs
sudo ln -fs /usr/local/lib/${IOJS}/bin/node /usr/local/bin/node
sudo ln -fs /usr/local/lib/${IOJS}/bin/npm /usr/local/bin/npm

echo "> Upgrading npm to latest"
npm install -f npm -g

echo "iojs version: $(iojs -v), npm version: $(npm -v)"
