#!/bin/bash
set -e

mkdir -p ~/src && cd ~/src

echo "---- INSTALLING: setting up symbolic link for emacs"
ln -fs ~/dotfiles/emacs/emacs ~/.emacs
sudo ln -fs ~/dotfiles/bash/e /usr/bin/e

echo "---- INSTALLING: emacs dependencies"
sudo aptitude install -y libxaw7-dev
sudo apt-get install -y libtiff5-dev
sudo apt-get install -y libpng12-dev
sudo apt-get install -y libgif-dev
sudo apt-get install -y libncurses5-dev

EMACS_V=24.3
EMACS_BASE="emacs-$EMACS_V"
MIRROR="ftp://ftp.sunet.se"

if [ ! -d "$EMACS_BASE" ]; then
    echo "---- INSTALLING: $EMACS_BASE"
    EMACS_GZ="$EMACS_BASE.tar.gz"
    wget -O $EMACS_GZ "$MIRROR/pub/gnu/emacs/$EMACS_GZ"
    tar xvfz $EMACS_GZ
    cd $EMACS_BASE
    ./configure --with-jpeg=no --with-png=no --with-gif=no --with-tiff=no
    make -j `nproc`
    sudo make install
    cd ~/src && rm $EMACS_GZ
else
    echo "---- INSTALLING: $EMACS_BASE already installed, SKIPPING!"
fi

cd ~/src
JSHINT=jshint-mode

if [ ! -d "$JSHINT" ]; then
    echo "---- INSTALLING: jshint-mode for emacs"
    git clone git://github.com/daleharvey/$JSHINT.git
else
    echo "---- INSTALLING: $JSHINT already installed, SKIPPING!"
fi
