#!/bin/bash
set -e

mkdir -p ~/src && cd ~/src

PIDGIN_V=2.10.6
PIDGIN_FOLDER="pidgin-$PIDGIN_V"

if [ ! -d "$PIDGIN_FOLDER" ]; then
    echo "---- INSTALLING: build-dep pidgin"
    sudo apt-get --assume-yes build-dep pidgin

    echo "---- INSTALLING: pidgin (and finch)"
    PIDGIN_FILE=$PIDGIN_FOLDER.tar.bz2
    PIDGIN_URL="http://downloads.sourceforge.net/project/pidgin/Pidgin/$PIDGIN_V/$PIDGIN_FILE?r=&ts=1351971096&use_mirror=garr"
    wget -O $PIDGIN_FILE $PIDGIN_URL
    tar xjvf $PIDGIN_FILE
    cd $PIDGIN_FOLDER
    NUMBER_OF_PROCESSORS=`cat /proc/cpuinfo | grep processor | wc -l`
    ./configure && make -j $NUMBER_OF_PROCESSORS && sudo make install && sudo ldconfig
    cd ..
    rm $PIDGIN_FILE
fi
