#!/bin/bash

sudo apt-get -y install apt-transport-https

curl https://repo.varnish-cache.org/ubuntu/GPG-key.txt | sudo apt-key add -

echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-4.0" | sudo tee -a /etc/apt/sources.list.d/varnish-cache.list

sudo apt-get -y update

sudo apt-get -y install varnish

sudo apt-get -y install libvarnishapi-dev
