#!/bin/bash

set -e

mkdir -p ~/src && cd ~/src

echo "---- INSTALLING: libtool (for various configure, automake stuff)"
sudo apt-get install -y libtool

if [ ! -d "ldb" ]; then
    git clone git://github.com/hij1nx/ldb.git && cd ldb
    make configure && make clean && make && sudo make install
fi
