#!/bin/bash
set -e

echo "---- INSTALLING: setting up folder structure for gnome-terminal "
mkdir -p ~/.gconf/apps/gnome-terminal/profiles/Default

echo "---- INSTALLING: symlink for gnome-terminal %gconf.xml"
ln -fs ~/dotfiles/%gconf.xml ~/.gconf/apps/gnome-terminal/profiles/Default/%gconf.xml

echo "---- INSTALLING: gnome-terminal"
sudo apt-get install --assume-yes gnome-terminal

