#!/bin/bash

echo "---- INSTALLING: irssi"
sudo apt-get install -y irssi

echo "---- INSTALLING: irssi-plugin-otr"
sudo apt-get install -y irssi-plugin-otr

echo "---- INSTALLING: irssi configuration"
mkdir -p ~/.irssi
ln -fs ~/dotfiles/irssi/config ~/.irssi/config
