#!/bin/bash
set -e

echo "---- INSTALLING: installing global npm modules"
npm install -g browserify
npm install -g forever
npm install -g nave
npm install -g morkdown
npm install -g node-gyp
npm install -g cordova

# serve static stuff, browserify on change and do live reload
npm install -g beefy

# for doing e.g. "wr 'browserify index.js -o bundle.js' & serve www/"
npm install -g wr
npm install -g serve

#npm install -g rsa-json
#npm install -g swank-js
#npm install -g uglify-js2
npm install -g node-inspector

npm install -g pkginit
pkginit add default /home/magnus/dotfiles/node/default.json

