#!/bin/bash
set -e

SCRIPT_DIR=$( cd "$( dirname "$0" )" && pwd )

echo "---- INSTALLING: setting up folder structure"
mkdir -p ~/local ~/src

echo "---- INSTALLING: symlinks"
ln -fs $SCRIPT_DIR/bash/bashrc ~/.bashrc
ln -fs $SCRIPT_DIR/git/gitconfig ~/.gitconfig
ln -fs $SCRIPT_DIR/emacs/emacs ~/.emacs
ln -fs $SCRIPT_DIR/ssh/config ~/.ssh/config
sudo ln -fs $SCRIPT_DIR/bash/e /usr/bin/e
sudo ln -fs $SCRIPT_DIR/rc.local /etc/rc.local

source "install-common"
source "install-pidgin"
source "install-node"
source "install-npm-modules"

# add in bundles from bundle.txt
#mkdir -p ~/.vim/bundle
#bundles=$(cat ./bundles.txt)
#cd ~/.vim/bundle
#for repo in $bundles; do
#    git clone $repo
#done
