#!/bin/bash
set -e

echo "---- INSTALLING: setting up folder structure for gnome-terminal "
GT_DEFAULT=~/.gconf/apps/gnome-terminal/profiles/Default
mkdir -p $GT_DEFAULT

echo "---- INSTALLING: symlink for gnome-terminal %gconf.xml"
ln -fs ~/dotfiles/%gconf.xml $GT_DEFAULT/%gconf.xml

echo "---- INSTALLING: gnome-terminal"
sudo apt-get install --assume-yes gnome-terminal

