#!/bin/bash
set -e

mkdir -p ~/src && cd ~/src

echo "---- INSTALLING: bitcoin"
sudo apt-get install -y qt4-qmake libqt4-dev build-essential libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev
sudo apt-get install -y libdb5.1++-dev
sudo apt-get install -y libprotobuf-dev

if [ ! -d "bitcoin" ]; then
    git clone git://github.com/bitcoin/bitcoin.git && cd bitcoin
    NUMBER_OF_PROCESSORS=`cat /proc/cpuinfo | grep processor | wc -l`
    ./autogen.sh
    ./configure --with-incompatible-bdb
    make -j $NUMBER_OF_PROCESSORS
fi




