#!/bin/bash

# http://sourceforge.net/p/ddclient/wiki/Home/
# https://fusion.easydns.com/index.php?/Knowledgebase/Article/View/102/7/dynamic-dns

sudo apt-get install -y ddclient
sudo cp ~/dotfiles/dns/ddclient.conf /etc/ddclient.conf
