#!/bin/bash
set -e

mkdir -p ~/src && cd ~/src

echo "---- INSTALLING: setting up symbolic link for emacs"
ln -fs ~/dotfiles/emacs/emacs ~/.emacs
sudo ln -fs ~/dotfiles/bash/e /usr/bin/e

echo "---- INSTALLING: emacs dependencies"
sudo aptitude install libxaw7-dev
#sudo apt-get install --assume-yes libtiff4-dev libjpeg-dev libgif-dev libxpm-dev libncurses5-dev
sudo apt-get install --assume-yes libncurses5-dev

EMACS_V=24.2
EMACS_BASE="emacs-$EMACS_V"

if [ ! -d "$EMACS_BASE" ]; then
    echo "---- INSTALLING: $EMACS_BASE"
    EMACS_GZ="$EMACS_BASE.tar.gz"
    wget -O $EMACS_GZ "ftp://ftp.gnu.org/pub/gnu/emacs/$EMACS_GZ"
    tar xvfz $EMACS_GZ
    cd $EMACS_BASE
    ./configure --with-jpeg=no --with-png=no --with-gif=no --with-tiff=no
    NUMBER_OF_PROCESSORS=`cat /proc/cpuinfo | grep processor | wc -l`
    make -j $NUMBER_OF_PROCESSORS
    sudo make install
    cd ~/src && rm $EMACS_GZ
else
    echo "---- INSTALLING: $EMACS_BASE already installed, SKIPPING!"
fi

cd ~/src
JSHINT=jshint-mode

if [ ! -d "$JSHINT" ]; then
    echo "---- INSTALLING: jshint-mode for emacs"
    git clone git://github.com/daleharvey/$JSHINT.git
else
    echo "---- INSTALLING: $JSHINT already installed, SKIPPING!"
fi
