#!/bin/bash

set -e

mkdir -p ~/src/build_maidsafe && cd ~/src

sudo apt-get update
sudo apt-get install -y build-essential cmake python-psutil libfuse-dev git-all libicu-dev valgrind binutils-gold

if [ ! -d "MaidSafe" ]; then
    git clone git@github.com:maidsafe/MaidSafe.git
    git -C MaidSafe submodule update --init
    cd build_maidsafe
    cmake ../MaidSafe -DCMAKE_BUILD_TYPE=Debug
fi



