#!/bin/bash
set -e

echo "---- INSTALLING: sshfs"
sudo apt-get install --assume-yes sshfs
echo "---- INSTALLING: openssh-server"
sudo apt-get install --assume-yes openssh-server
sudo cp ~/dotfiles/ssh/sshd_config /etc/ssh
