#!/bin/bash

curl -fsSkL https://raw.github.com/cask/cask/master/go | python

#Successfully installed Cask!  Now, add the cask binary to your $PATH:
#  export PATH="/home/lms/.cask/bin:$PATH"

# I renamed ~/.cask to ~/dotfiles/emacs/cask
