#!/bin/bash
set -e

echo "---- INSTALLING: .ssh folder structure"
mkdir -p ~/.ssh
echo "---- INSTALLING: symlink for ~/.ssh/config"
ln -fs ~/dotfiles/ssh/config ~/.ssh/config
echo "---- INSTALLING: sshfs"
sudo apt-get install --assume-yes sshfs
echo "---- INSTALLING: openssh-server"
sudo apt-get install --assume-yes openssh-server
sudo cp ~/dotfiles/ssh/sshd_config /etc/ssh
