#!/bin/bash
set -e

cd ~/src

NODE_V=v0.8.14
echo "---- INSTALLING: node $NODE_V"

if [ ! -d "node" ]; then
    git clone git://github.com/joyent/node.git
fi

cd node && rm -rf out
git co $NODE_V
NUMBER_OF_PROCESSORS=`cat /proc/cpuinfo | grep processor | wc -l`
./configure && time make -j $NUMBER_OF_PROCESSORS && sudo make install
