#!/bin/bash
set -e

mkdir -p ~/src && cd ~/src

echo "---- INSTALLING: bitcoin"
sudo add-apt-repository ppa:bitcoin/bitcoin -y
sudo apt-get update --assume-yes
sudo apt-get install --assume-yes qt4-qmake libqt4-dev build-essential libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libdb4.8++-dev

if [ ! -d "bitcoin" ]; then
    git clone git://github.com/ralphtheninja/bitcoin.git && cd bitcoin
    NUMBER_OF_PROCESSORS=`cat /proc/cpuinfo | grep processor | wc -l`
    # check out version
    git co v0.8.5
    # make bitcoin-qt
    qmake "USE_UPNP=-" && make -j $NUMBER_OF_PROCESSORS
    # make bitcoind
    cd src && make -f makefile.unix -j $NUMBER_OF_PROCESSORS bitcoind USE_UPNP=-
fi




