#!/bin/bash
set -e

mkdir -p ~/src && cd ~/src

echo "---- INSTALLING: litecoin"
sudo apt-get install -y libboost-all-dev libssl-dev libdb++-dev libminiupnpc-dev

if [ ! -d "litecoin" ]; then
    git clone https://github.com/litecoin-project/litecoin.git && cd litecoin
    cd src && make -f makefile.unix -j `nproc` litecoind
fi




