# get dir for this script
SOURCE="${BASH_SOURCE[0]}"
THIS="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do 
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$THIS/$SOURCE"
    THIS="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
    done
THIS="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source $THIS/alias.bash
source $THIS/colors.bash
source $THIS/git.bash
source $THIS/npm-completion.bash

export N_PREFIX=~/local
export PATH=~/local/bin:$PATH

# enable bash completion in interactive shells
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
   . /etc/bash_completion
fi

