# get dir for this script
SOURCE="${BASH_SOURCE[0]}"
THIS="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$THIS/$SOURCE"
    THIS="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
    done
THIS="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

NUMBER_OF_PROCESSORS=`cat /proc/cpuinfo | grep processor | wc -l`

source $THIS/alias.bash
source $THIS/colors.bash
source $THIS/git-completion.bash
source $THIS/prompt.bash
source $THIS/npm-completion.bash
source $THIS/tools.bash

prepend_to_path() {
    if [[ ":$PATH:" != *":$1:"* ]]; then
        PATH=$1:$PATH
    fi
}

append_to_path() {
    if [[ ":$PATH:" != *":$1:"* ]]; then
        PATH=$PATH:$1
    fi
}

prepend_to_path ~/dotfiles/work/arris
prepend_to_path ~/local/bin
prepend_to_path ~/dotfiles/bash
prepend_to_path ~/dotfiles/bin
prepend_to_path ~/dotfiles/node

#append_to_path ~/local/gradle-1.10/bin

# AndroidDev PATH
#export PATH=${PATH}:~/android-sdk-linux/tools
#export PATH=${PATH}:~/android-sdk-linux/platform-tools
#export JAVA_HOME=/usr/

# prevent git from opening editor for merge commit message
export GIT_MERGE_AUTOEDIT=no

# when opening eclipse, make sure the menu is attached to the window
export UBUNTU_MENUPROXY=0

# enable bash completion in interactive shells
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
   . /etc/bash_completion
fi

export GRADLE_OPTS="-Xmx1g -XX:MaxPermSize=256m"