#!/bin/bash

edit() {
    local FILE=$1

    if [[ -z $FILE ]]; then
	exec emacsclient -a "" -n -c -e "(fullscreen)"
        return
    fi

    if [ $FILE[0] != "/" -o $FILE[0] = "~" ]
    then
        FILE="$PWD/$FILE"
    fi

    exec emacsclient -a "" -n -c -e "(find-file \"$FILE\")" "(fullscreen)"
}

edit $1
