#PS1="$BRIGHT_GREEN\u@\h$WHITE|$BRIGHT_RED\$(date +%H:%M)$WHITE|$BRIGHT_CYAN\w\$(parse_git_branch) $BRIGHT_VIOLET\$ $WHITE"
export PS1="$BRIGHT_GREEN\u@\h$WHITE|$BRIGHT_RED\$(date +%H:%M)$WHITE|$BRIGHT_CYAN\w\$(__git_ps1) $BRIGHT_VIOLET\$ $WHITE";
